// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/file/getfile": {
            "post": {
                "description": "此接口生成的 url 地址；含有时效性；不建议作为长时间显示。",
                "tags": [
                    "文件"
                ],
                "summary": "根据 hash 获取文件的 url 地址",
                "parameters": [
                    {
                        "description": "文件的hash列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.GetFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/controller.GetFileResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/file/getfile/:hash": {
            "get": {
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "根据 url 地址；下载文件;",
                "parameters": [
                    {
                        "type": "string",
                        "description": "哈希地址",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "过期时间",
                        "name": "expred",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名",
                        "name": "signature",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件二进制数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "format": "int32"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/file/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "保存用户上传的文件",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "csv",
                        "description": "文件列表",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/controller.UploadResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/file/{hash}": {
            "get": {
                "description": "注意该接口没有做任何权限验证；慎用；请使用 GetFile 接口获取带有时效性的 url 地址。",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "根据 hash 直接返回文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "哈希地址",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件二进制数据",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "format": "int32"
                            }
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/:id": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "根据用户ID获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/avatar": {
            "put": {
                "tags": [
                    "用户"
                ],
                "summary": "用改用户头像;注意是存hash地址；而不是 url 地址;",
                "parameters": [
                    {
                        "description": "修改头像请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UserPutAvatarRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/get": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.UserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/logout": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/nickname": {
            "put": {
                "tags": [
                    "用户"
                ],
                "summary": "用改用户中文名称;",
                "parameters": [
                    {
                        "description": "修改中文名称请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UserPutNicknameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/password": {
            "put": {
                "description": "成功后；服务端将清除当前用户token的登录状态",
                "tags": [
                    "用户"
                ],
                "summary": "修改用户密码;",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UserPutPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        },
        "/users/users": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "根据 search 关键字 获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "搜索关键字",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.KResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.KResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.GetFileRequest": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controller.GetFileResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "controller.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controller.UploadResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "description": "文件名称",
                    "type": "string"
                },
                "hash": {
                    "description": "文件 hash 地址",
                    "type": "string"
                },
                "size": {
                    "description": "文件大小 字节",
                    "type": "integer"
                }
            }
        },
        "controller.UserPutAvatarRequest": {
            "type": "object",
            "required": [
                "avatar"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                }
            }
        },
        "controller.UserPutNicknameRequest": {
            "type": "object",
            "required": [
                "nickname"
            ],
            "properties": {
                "nickname": {
                    "type": "string"
                }
            }
        },
        "controller.UserPutPasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "avatar",
                "id",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像、创建时；为空字符串;注意只是保存 文件的hash 地址；而不是 URL 地址",
                    "type": "string",
                    "example": "''"
                },
                "createAt": {
                    "type": "string"
                },
                "id": {
                    "description": "用户 ID;其类型是一个 uint 类型",
                    "type": "integer"
                },
                "nickname": {
                    "description": "用户中文名称，默认为 ‘’，可后期通过修改用户信息设置",
                    "type": "string"
                },
                "updateAt": {
                    "type": "string"
                },
                "username": {
                    "description": "用户账户；创建时使用；后期不可修改。",
                    "type": "string",
                    "example": "whx"
                }
            }
        },
        "model.UserResponse": {
            "type": "object",
            "required": [
                "avatar",
                "id",
                "token",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像、创建时；为空字符串;注意只是保存 文件的hash 地址；而不是 URL 地址",
                    "type": "string",
                    "example": "''"
                },
                "createAt": {
                    "type": "string"
                },
                "id": {
                    "description": "用户 ID;其类型是一个 uint 类型",
                    "type": "integer"
                },
                "nickname": {
                    "description": "用户中文名称，默认为 ‘’，可后期通过修改用户信息设置",
                    "type": "string"
                },
                "token": {
                    "description": "认证令牌",
                    "type": "string"
                },
                "updateAt": {
                    "type": "string"
                },
                "username": {
                    "description": "用户账户；创建时使用；后期不可修改。",
                    "type": "string",
                    "example": "whx"
                }
            }
        },
        "utils.KResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "go-net",
	Description:      "一个 IM 服务器\n支持用户注册、登录、好友管理、群组聊天\n基于 Go + Gin + GORM + Redis\n目前访问服务器任何接口: localhost:8080/api 前端可用先使用代理设置\n使用文件 hash 获取文件地址可用先固定: localhost:8080/api/file/:hash 前端可用看作做;方便后期迁移",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
