basePath: /api
definitions:
  controller.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controller.UserPutAvatarRequest:
    properties:
      avatar:
        type: string
    required:
    - avatar
    type: object
  controller.UserPutPasswordRequest:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  model.User:
    properties:
      avatar:
        description: 用户头像、创建时；为空字符串
        example: ''''''
        type: string
      createAt:
        type: string
      id:
        allOf:
        - $ref: '#/definitions/model.UserID'
        description: 用户 ID
        example: 1
      nickname:
        description: 用户中文名称，默认为 ‘’，可后期通过修改用户信息设置
        type: string
      updateAt:
        type: string
      username:
        description: 用户账户；创建时使用；后期不可修改。
        example: whx
        type: string
    required:
    - avatar
    - id
    - username
    type: object
  model.UserID:
    enum:
    - 0
    type: integer
    x-enum-varnames:
    - InvalidUserID
  model.UserResponse:
    properties:
      avatar:
        description: 用户头像、创建时；为空字符串
        example: ''''''
        type: string
      createAt:
        type: string
      id:
        allOf:
        - $ref: '#/definitions/model.UserID'
        description: 用户 ID
        example: 1
      nickname:
        description: 用户中文名称，默认为 ‘’，可后期通过修改用户信息设置
        type: string
      token:
        description: 认证令牌
        type: string
      updateAt:
        type: string
      username:
        description: 用户账户；创建时使用；后期不可修改。
        example: whx
        type: string
    required:
    - avatar
    - id
    - token
    - username
    type: object
  utils.KResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 一个  IM 服务器
  title: go-net
  version: "1.0"
paths:
  /users/:id:
    get:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserResponse'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 根据用户ID获取用户信息
      tags:
      - 用户
  /users/avatar:
    put:
      parameters:
      - description: 修改头像请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.UserPutAvatarRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 用改用户头像;
      tags:
      - 用户
  /users/get:
    get:
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserResponse'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 获取用户信息
      tags:
      - 用户
  /users/login:
    post:
      parameters:
      - description: 登录请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.RegisterRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.UserResponse'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 用户登录
      tags:
      - 用户
  /users/logout:
    get:
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 退出登录
      tags:
      - 用户
  /users/password:
    put:
      description: 成功后；服务端将清除当前用户token的登录状态
      parameters:
      - description: 修改密码请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.UserPutPasswordRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 修改用户密码;
      tags:
      - 用户
  /users/register:
    post:
      parameters:
      - description: 注册请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.RegisterRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 用户注册
      tags:
      - 用户
  /users/users:
    get:
      parameters:
      - default: '""'
        description: 搜索关键字
        in: query
        name: search
        type: string
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 根据 search 关键字 获取用户列表
      tags:
      - 用户
swagger: "2.0"
