basePath: /api
definitions:
  controller.GetFileRequest:
    properties:
      files:
        items:
          type: string
        type: array
    type: object
  controller.GetFileResponse:
    properties:
      hash:
        type: string
      url:
        type: string
    type: object
  controller.GetPrivateMessagesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Message'
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
  controller.PutRequesetRequestResponse:
    properties:
      status:
        description: 状态 `status` tinyint(1) DEFAULT '0' COMMENT '0-待确认, 1-已确认, 2-已拒绝,
          3-已删除',
        type: integer
    type: object
  controller.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controller.RequestResponse:
    properties:
      friendID:
        description: 好友的 用户ID (类型 uint)
        type: integer
      remark:
        description: 备注信息
        type: string
    type: object
  controller.UploadResponse:
    properties:
      filename:
        description: 文件名称
        type: string
      hash:
        description: 文件 hash 地址
        type: string
      size:
        description: 文件大小 字节
        type: integer
    type: object
  controller.UserPutAvatarRequest:
    properties:
      avatar:
        type: string
    required:
    - avatar
    type: object
  controller.UserPutNicknameRequest:
    properties:
      nickname:
        type: string
    required:
    - nickname
    type: object
  controller.UserPutPasswordRequest:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  model.ChannelType:
    enum:
    - 0
    - 1
    - 2
    format: int32
    type: integer
    x-enum-varnames:
    - ChannelTypeNORMAL
    - ChannelTypePING
    - ChannelTypePONG
  model.Element:
    properties:
      content:
        description: 消息内容（文本内容或文件 HASH）
        type: string
      hash:
        description: 文件信息（仅在 Type 为图片/视频/文件时有效）
        type: string
      height:
        type: integer
      name:
        type: string
      size:
        type: integer
      type:
        allOf:
        - $ref: '#/definitions/model.MessageType'
        description: 消息类型（0：文本，1：图片，2：视频，3：文件）
      url:
        type: string
      width:
        type: integer
    type: object
  model.Friend:
    properties:
      createdAt:
        type: string
      friendId:
        description: 好友的 用户ID (类型 uint)
        type: integer
      id:
        description: 唯一 ID
        type: integer
      remark:
        description: 发起好友申请时备注时的备注
        type: string
      status:
        allOf:
        - $ref: '#/definitions/model.RequestFriendStatus'
        description: '状态:  `status` tinyint(1) DEFAULT ''0'' COMMENT ''0-待确认, 1-已确认,
          2-已拒绝, 3-已删除'','
      updatedAt:
        type: string
      userId:
        description: 自身的 ID 和当前登录的 用户 ID 一直。 (类型 uint)
        type: integer
    type: object
  model.FriendResponse:
    properties:
      avatar:
        description: 用户头像
        type: string
      createdAt:
        type: string
      friendId:
        description: 好友的 用户ID (类型 uint)
        type: integer
      id:
        description: 唯一 ID
        type: integer
      isOnline:
        description: 在线状态
        type: boolean
      nickname:
        description: 用户中文名称
        type: string
      remark:
        description: 发起好友申请时备注时的备注
        type: string
      status:
        allOf:
        - $ref: '#/definitions/model.RequestFriendStatus'
        description: '状态:  `status` tinyint(1) DEFAULT ''0'' COMMENT ''0-待确认, 1-已确认,
          2-已拒绝, 3-已删除'','
      updatedAt:
        type: string
      userId:
        description: 自身的 ID 和当前登录的 用户 ID 一直。 (类型 uint)
        type: integer
      username:
        description: 用户账号
        type: string
    type: object
  model.Message:
    properties:
      createdAt:
        type: string
      elements:
        description: 消息元素列表（JSON 序列化存储）
        items:
          $ref: '#/definitions/model.Element'
        type: array
      id:
        description: 消息 数据库索引
        type: integer
      msgId:
        description: 消息唯一 ID（客户端生成，保证幂等性）
        type: string
      receiverId:
        description: 消息接收者 ID
        type: integer
      senderId:
        description: 消息发送者 ID
        type: integer
      status:
        type: integer
      type:
        allOf:
        - $ref: '#/definitions/model.ChannelType'
        description: 消息类型 0：普通消息 1：ping 2：pong
    type: object
  model.MessageType:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - MsgTypeText
    - MsgTypeImage
    - MsgTypeVideo
    - MsgTypeFile
  model.RequestFriendStatus:
    enum:
    - 0
    - 1
    - 2
    - 3
    format: int32
    type: integer
    x-enum-comments:
      FriendStatusAccepted: 已确认
      FriendStatusDeleted: 已删除
      FriendStatusPending: 待确认
      FriendStatusRejected: 已拒绝
    x-enum-descriptions:
    - 待确认
    - 已确认
    - 已拒绝
    - 已删除
    x-enum-varnames:
    - FriendStatusPending
    - FriendStatusAccepted
    - FriendStatusRejected
    - FriendStatusDeleted
  model.User:
    properties:
      avatar:
        description: 用户头像、创建时；为空字符串;注意只是保存 文件的hash 地址；而不是 URL 地址
        example: ''''''
        type: string
      createAt:
        type: string
      id:
        description: 用户 ID;其类型是一个 uint 类型
        type: integer
      nickname:
        description: 用户中文名称，默认为 ‘’，可后期通过修改用户信息设置
        type: string
      updateAt:
        type: string
      username:
        description: 用户账户；创建时使用；后期不可修改。
        example: whx
        type: string
    required:
    - avatar
    - id
    - username
    type: object
  model.UserResponse:
    properties:
      avatar:
        description: 用户头像、创建时；为空字符串;注意只是保存 文件的hash 地址；而不是 URL 地址
        example: ''''''
        type: string
      createAt:
        type: string
      id:
        description: 用户 ID;其类型是一个 uint 类型
        type: integer
      nickname:
        description: 用户中文名称，默认为 ‘’，可后期通过修改用户信息设置
        type: string
      token:
        description: 认证令牌
        type: string
      updateAt:
        type: string
      username:
        description: 用户账户；创建时使用；后期不可修改。
        example: whx
        type: string
    required:
    - avatar
    - id
    - token
    - username
    type: object
  utils.KResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: |-
    一个 IM 服务器
    支持用户注册、登录、好友管理、群组聊天
    基于 Go + Gin + GORM + Redis
    目前访问服务器任何接口: localhost:8080/api 前端可用先使用代理设置
    使用文件 hash 获取文件地址可用先固定: localhost:8080/api/file/:hash 前端可用看作做;方便后期迁移
  title: go-net
  version: "1.0"
paths:
  /file/{hash}:
    get:
      description: 注意该接口没有做任何权限验证；慎用；请使用 GetFile 接口获取带有时效性的 url 地址。
      parameters:
      - description: 哈希地址
        in: path
        name: hash
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: 文件二进制数据
          schema:
            items:
              format: int32
              type: integer
            type: array
        "404":
          description: 文件不存在
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 根据 hash 直接返回文件
      tags:
      - 文件
  /file/getfile:
    post:
      description: 此接口生成的 url 地址；含有时效性；不建议作为长时间显示。
      parameters:
      - description: 文件的hash列表
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.GetFileRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/controller.GetFileResponse'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 根据 hash 获取文件的 url 地址
      tags:
      - 文件
  /file/getfile/:hash:
    get:
      parameters:
      - description: 哈希地址
        in: path
        name: hash
        required: true
        type: string
      - description: 过期时间
        in: query
        name: expred
        required: true
        type: string
      - description: 签名
        in: query
        name: signature
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: 文件二进制数据
          schema:
            items:
              format: int32
              type: integer
            type: array
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 根据 url 地址；下载文件;
      tags:
      - 文件
  /file/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - collectionFormat: csv
        description: 文件列表
        in: formData
        items:
          type: file
        name: files
        required: true
        type: array
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/controller.UploadResponse'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 保存用户上传的文件
      tags:
      - 文件
  /friends/{id}:
    put:
      description: 如果将好友移除；同时也会移除对方的好友关系
      parameters:
      - description: 修改好友申请状态;好友列表（表的 ID）
        in: path
        name: id
        required: true
        type: integer
      - description: 修改好友申请状态
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.PutRequesetRequestResponse'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/controller.PutRequesetRequestResponse'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 修改好友申请状态,可用于 同意(1),拒绝(2)、删除(3)
      tags:
      - 好友模块
  /friends/friends:
    get:
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.FriendResponse'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 获取好友列表
      tags:
      - 好友模块
  /friends/request:
    post:
      description: |-
        好友表没有关系则新增一条记录 status = 0
        好友表中已经存在；且 status != 1 或 != 0时；则重新更新 status = 0 和 remark(如果有传递)
        好友表中已经存在；且 status == 1 或 = 0时；不会有任何变化；返回成功
      parameters:
      - description: 发起好友申请
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.RequestResponse'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.Friend'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 发起好友申请
      tags:
      - 好友模块
  /friends/requests:
    get:
      description: user_id = 当前登录的代表主动发起申请(等待别人反馈)；否则；是其他用户(friend_id)向当前用户发起生气 [同意，拒绝]
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.FriendResponse'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 获取申请列表
      tags:
      - 好友模块
  /groups:
    get:
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserResponse'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 获取群列表
      tags:
      - 群
  /messages/private/:friendID:
    get:
      parameters:
      - default: 20
        description: 限制条数
        in: query
        name: limit
        type: integer
      - default: 0
        description: 偏移量
        in: query
        name: offset
        type: integer
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/controller.GetPrivateMessagesResponse'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 获取与好友的历史记录
      tags:
      - 好友消息
  /users/:id:
    get:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 根据用户ID获取用户信息
      tags:
      - 用户
  /users/avatar:
    put:
      parameters:
      - description: 修改头像请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.UserPutAvatarRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 用改用户头像;注意是存hash地址；而不是 url 地址;
      tags:
      - 用户
  /users/get:
    get:
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.UserResponse'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 获取用户信息
      tags:
      - 用户
  /users/login:
    post:
      parameters:
      - description: 登录请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.RegisterRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.UserResponse'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 用户登录
      tags:
      - 用户
  /users/logout:
    get:
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 退出登录
      tags:
      - 用户
  /users/nickname:
    put:
      parameters:
      - description: 修改中文名称请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.UserPutNicknameRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 用改用户中文名称;
      tags:
      - 用户
  /users/password:
    put:
      description: 成功后；服务端将清除当前用户token的登录状态
      parameters:
      - description: 修改密码请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.UserPutPasswordRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 修改用户密码;
      tags:
      - 用户
  /users/register:
    post:
      parameters:
      - description: 注册请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.RegisterRequest'
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 用户注册
      tags:
      - 用户
  /users/users:
    get:
      parameters:
      - default: '""'
        description: 搜索关键字
        in: query
        name: search
        type: string
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/utils.KResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/utils.KResponse'
      summary: 根据 search 关键字 获取用户列表
      tags:
      - 用户
swagger: "2.0"
